[package]
name = "async-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "iouring"
path = "src/iouring.rs"

[[bin]]
name = "iouring"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
tokio-uring = "0.4.0"
